import crypto from 'node:crypto';
import fs from 'node:fs';

export const TV_SOURCES = ['marks.js', 'app.js', 'look.js'];
const sha = (s) => crypto.createHash('sha256').update(s).digest('hex').slice(0, 16);
// Each built file names the hash of the source it came from, so a test can catch a stale build.
export const tvHeader = (f) => `// GENERATED by scripts/build-tv.mjs from public/${f} (source sha256 ${sha(fs.readFileSync(`public/${f}`, 'utf8'))}). Do not edit.\n`;
const lower = (html) => html.replace(/<script src="\/(marks|app|look)\.js"><\/script>/g, '<script src="/tv/$1.js"></script>');
export const tvHtml = () => lower(fs.readFileSync('public/index.html', 'utf8'));
export const tvLookHtml = () => lower(fs.readFileSync('public/look.html', 'utf8'));
