import crypto from 'node:crypto';
import fs from 'node:fs';

export const TV_SOURCES = ['marks.js', 'view.js', 'app.js', 'look.js', 'widget.js', 'settings.js'];
export const TV_PAGES = [['index.html', 'tv.html'], ['look.html', 'tv-look.html'], ['widget.html', 'tv-widget.html'], ['settings.html', 'tv-settings.html']];
const sha = (s) => crypto.createHash('sha256').update(s).digest('hex').slice(0, 16);
// Each built file names the hash of the source it came from, so a test can catch a stale build.
export const tvHeader = (f) => `// GENERATED by scripts/build-tv.mjs from public/${f} (source sha256 ${sha(fs.readFileSync(`public/${f}`, 'utf8'))}). Do not edit.\n`;
const lower = (html) => html.replace(/<script src="\/(marks|view|app|look|widget|settings)\.js"><\/script>/g, '<script src="/tv/$1.js"></script>');
export const tvPage = (src) => lower(fs.readFileSync(`public/${src}`, 'utf8'));
export const tvHtml = () => tvPage('index.html');
export const tvLookHtml = () => tvPage('look.html');
